const translations = {
    en: {
        homeTitle: "My Portfolio",
        homeDescription: "Transforming creative ideas into stunning images.",
        readMoreButton: "Read More",
        informationTitle: "Information",
        contactTitle: "Contact Me",
        nameLabel: "Name:",
        emailLabel: "Email:",
        messageLabel: "Message:",
        submitButton: "Send",
        footerText: "© 2024 Marius Vision",
        portfolioTitle: "My Work",
        workProject1Title: "Project 1",
        workDescription1: "Project description in English.",
        workProject2Title: "Project 2",
        workDescription2: "Another project description in English.",
        idealClientsTitle: "Ideal Clients",
        idealClientsText: "I love working with clients who value collaboration and are open to creative input. If you’re comfortable sharing your thoughts and welcome guidance on composition, color theory, and design aesthetics, I’m confident that together, we can bring your vision to life in a way that truly captures its essence and emotion.",
        commonChallengesTitle: "Common Client Challenges",
        commonChallengesText: "Have you been frustrated by designers who say your ideas are too complicated? Are you tired of hearing that the only solutions available involve high costs and compromise? Or maybe you’ve worked with designers who just don’t 'get' the feeling you’re trying to convey. If any of this resonates with you, you’re in the right place.",
        whyChooseTitle: "Why Choose Marius Vision?",
        whyChooseText: "With over 50 completed projects and my work featured in Women’s Wear Daily, I am dedicated to pushing the boundaries of graphic design. Whether it’s photo editing and manipulation, product photography, or architectural rendering, I embrace every challenge—no idea is too difficult. At Marius Vision, imagination is the only limit. Let’s start a conversation about your next project.",
        whatIDontDoTitle: "What I Don't Do",
        whatIDontDoText: "If you're looking for CGI videos or expect a one-and-done transaction without ongoing collaboration, I might not be the best fit for you. Achieving the perfect result requires your feedback along the way—just a few simple comments at least to ensure we’re heading in the right direction.",
        aboutMeTitle: "About Me",
        aboutMeText: "I’m Marius Hagelskjær, a seasoned graphic designer from Denmark. With experience on platforms like Fiverr, I’ve honed my skills in Adobe Photoshop, Adobe Illustrator, and various aspects of 3D modeling and rendering. When I’m not crafting visuals, you’ll find me taking photos, traveling, or fighting on the tatami.",
        processTitle: "The Process",
        initialContactTitle: "Initial Contact",
        initialContactText: "The first step is reaching out to me with your project idea. This can be done via the contact form or directly through email. I’ll then set up a shared workspace on Notion for us to collaborate effectively.",
        sharedWorkspaceTitle: "Shared Workspace",
        sharedWorkspaceText: "In Notion, you'll have access to a dedicated space where you can follow the progress of your project. Here, we’ll discuss and agree on the project’s scope, mood, and budget. *(An example of a Notion workspace image can be included here.)*",
        upfrontPaymentTitle: "Upfront Payment",
        upfrontPaymentText: "To proceed, an upfront payment of $5 is required. This helps secure your spot in the project queue and initiates our work together.",
        feedbackProcessTitle: "Feedback Process",
        feedbackProcessText: "The feedback process is where the magic happens. It’s a collaborative phase where you review the progress and provide feedback. Your involvement is crucial to ensure the final product aligns with your vision.",
        finalDeliveryTitle: "Final Delivery",
        finalDeliveryText: "Once the project is complete and all feedback has been incorporated, you’ll receive the final product. We’ll ensure that everything meets your expectations before finalizing the project."
    },
    es: {
        homeTitle: "Mi Portafolio",
        homeDescription: "Transformando ideas creativas en imágenes impresionantes.",
        readMoreButton: "Leer Más",
        informationTitle: "Información",
        contactTitle: "Contáctame",
        nameLabel: "Nombre:",
        emailLabel: "Correo electrónico:",
        messageLabel: "Mensaje:",
        submitButton: "Enviar",
        footerText: "© 2024 Marius Vision",
        portfolioTitle: "Mi Trabajo",
        workProject1Title: "Proyecto 1",
        workDescription1: "Descripción del proyecto en español.",
        workProject2Title: "Proyecto 2",
        workDescription2: "Otra descripción del proyecto en español.",
        idealClientsTitle: "Clientes Ideales",
        idealClientsText: "Me encanta trabajar con clientes que valoran la colaboración y están abiertos a ideas creativas. Si estás cómodo compartiendo tus pensamientos y aceptas orientación sobre composición, teoría del color y estética del diseño, estoy seguro de que juntos podemos dar vida a tu visión de una manera que realmente capture su esencia y emoción.",
        commonChallengesTitle: "Desafíos Comunes de los Clientes",
        commonChallengesText: "¿Te has frustrado con diseñadores que dicen que tus ideas son demasiado complicadas? ¿Estás cansado de escuchar que las únicas soluciones disponibles implican altos costos y compromisos? O tal vez has trabajado con diseñadores que simplemente no 'entienden' el sentimiento que intentas transmitir. Si algo de esto resuena contigo, estás en el lugar correcto.",
        whyChooseTitle: "¿Por Qué Elegir Marius Vision?",
        whyChooseText: "Con más de 50 proyectos completados y mi trabajo presentado en Women's Wear Daily, estoy dedicado a empujar los límites del diseño gráfico. Ya sea edición y manipulación de fotos, fotografía de productos o renderización arquitectónica, acepto cada desafío—ninguna idea es demasiado difícil. En Marius Vision, la imaginación es el único límite. Comencemos una conversación sobre tu próximo proyecto.",
        whatIDontDoTitle: "Lo Que No Hago",
        whatIDontDoText: "Si estás buscando videos CGI o esperas una transacción de una sola vez sin colaboración continua, quizás no soy la mejor opción para ti. Obtener el resultado perfecto requiere tu feedback a lo largo del camino—solo unos pocos comentarios simples al menos para asegurarnos de que estamos en la dirección correcta.",
        aboutMeTitle: "Sobre Mí",
        aboutMeText: "Soy Marius Hagelskjær, un experimentado diseñador gráfico de Dinamarca. Con experiencia en plataformas como Fiverr, he perfeccionado mis habilidades en Adobe Photoshop, Adobe Illustrator y varios aspectos del modelado y renderizado 3D. Cuando no estoy creando visuales, me encontrarás tomando fotos, viajando o peleando en el tatami.",
        processTitle: "El Proceso",
        initialContactTitle: "Contacto Inicial",
        initialContactText: "El primer paso es contactarme con tu idea de proyecto. Esto se puede hacer a través del formulario de contacto o directamente por correo electrónico. Luego, configuraré un espacio compartido en Notion para que colaboremos de manera efectiva.",
        sharedWorkspaceTitle: "Espacio Compartido",
        sharedWorkspaceText: "En Notion, tendrás acceso a un espacio dedicado donde podrás seguir el progreso de tu proyecto. Aquí, discutiremos y acordaremos el alcance, el estado de ánimo y el presupuesto del proyecto. *(Se puede incluir una imagen del espacio de trabajo de Notion aquí.)*",
        upfrontPaymentTitle: "Pago Inicial",
        upfrontPaymentText: "Para proceder, se requiere un pago inicial de $5. Esto ayuda a asegurar tu lugar en la cola del proyecto e inicia nuestro trabajo juntos.",
        feedbackProcessTitle: "Proceso de Retroalimentación",
        feedbackProcessText: "El proceso de retroalimentación es donde ocurre la magia. Es una fase colaborativa donde revisas el progreso y proporcionas comentarios. Tu participación es crucial para asegurar que el producto final se alinee con tu visión.",
        finalDeliveryTitle: "Entrega Final",
        finalDeliveryText: "Una vez que el proyecto esté completo y todos los comentarios se hayan incorporado, recibirás el producto final. Nos aseguraremos de que todo cumpla con tus expectativas antes de finalizar el proyecto."
    },
    da: {
        homeTitle: "Min Portefølje",
        homeDescription: "Forvandler kreative ideer til fantastiske billeder.",
        readMoreButton: "Læs Mere",
        informationTitle: "Information",
        contactTitle: "Kontakt Mig",
        nameLabel: "Navn:",
        emailLabel: "E-mail:",
        messageLabel: "Besked:",
        submitButton: "Send",
        footerText: "© 2024 Marius Vision",
        portfolioTitle: "Mit Arbejde",
        workProject1Title: "Projekt 1",
        workDescription1: "Projekt
